### ISSUE TITLE
Consider to use set properties in ApiKey example

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [mihirdilip/authentication-serverside-samples#1]
I’ve used your example class https://github.com/mihirdilip/authentication-serverside-samples/blob/master/src/Authentication.ServerSide.ApiKey/ApiKey.cs, 
But wanted to populate values not from constructor, but from configuration.
services.Configure<List<ApiKey>>(Configuration.GetSection("ApiKeysList"));

It gave me not obvious  errors until I added default constructor   and set properties, I.e.

        //To load from configuration needs default constructor and  set properties 

        public ApiKey(){}

        public string Key { get; set; }
        public string OwnerName { get; set; }
        public IReadOnlyCollection<Claim> Claims { get; set; }

I suggest to add these changes to make your sample easier to extend 
or add another sample with read from configuration like
  "ApiKeysList": [ //The actual values should be in secret
    {
      "Key": "F3D35868-6862",
      "OwnerName": "Client 1"
    },
    {
      "Key": "E2F2A1FF-3FA9",
      "OwnerName": "Client 2"
    }
  ],

**Comment by mihirdilip** [comment]
@michael-freidgeim-webjet ,
I appreciate that you are using this sample and thank you for the feedback. I will keep this in mind when adding/changing these samples.

The reasoning behind not having setters in the sample was just so that once they are set, the values of properties should not be able to be amended easily by other parts of the code. 

Please note that these are just basic samples to show how to use the libraries. They may not be ready to use for production or cover all different ways you can achieve same thing in asp.net core.
 
I hope you were able to fix the issue by changing the class implementation. Please let me know if you come across any other problems when using these samples/libraries.
